# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "firewire_ohci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/da948a98-1b1b-4c06-98c9-1147173448ee";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0d892680-934c-437f-8ede-a42ef781c835";
      fsType = "ext4";
    };

  fileSystems."/tmp" =
    { device = "tmp";
      fsType = "tmpfs";
      options = [ "size=8g" "mode=1777" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d71e0b01-5042-4456-8a72-d4653d0b7e4e"; }
    ];

  nix.maxJobs = 2;
}
