# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3d369f1e-b1b5-4c36-90da-f34f2e0f6af0";
      fsType = "btrfs";
    };

  fileSystems."/tmp" =
    { device = "tmp";
      fsType = "tmpfs";
      options = [ "size=16G" "mode=1777" ];
    };

  fileSystems."/var/tmp" =
    { device = "vartmp";
      fsType = "tmpfs";
      options = [ "size=1G" "mode=1777" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/bf4791ad-62c0-481d-bc8c-a800ad9cf8f8";
      fsType = "ext4";
    };
    
  swapDevices =
    [ { device = "/dev/disk/by-uuid/58a029ec-27e3-49cd-9ec1-2452ede1cec5"; }
      { device = "/dev/disk/by-uuid/c4bd389b-dd2d-4777-a2f3-d55bbe000566"; }
    ];

  nix.maxJobs = 4;
}
