# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "subvol=subvolumes/sysroot" ];
    };

  fileSystems."/home" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "subvol=subvolumes/home" ];
    };

  fileSystems."/var" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "subvol=subvolumes/var" ];
    };

  fileSystems."/nix/store" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "subvol=subvolumes/store" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F8BB-5A15";
      fsType = "vfat";
    };

  fileSystems."/tmp" =
    { device = "temp";
      fsType = "tmpfs";
      options = [ "size=16G" "mode=1777" ];
    };

  fileSystems."/var/tmp" =
    { device = "vartmp";
      fsType = "tmpfs";
      options = [ "size=1G" "mode=1777" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "subvol=subvolumes/etc-nixos" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6567b6fd-c570-412e-8f53-b6ba1733640c"; }
    ];

  nix.maxJobs = 4;
}
