#!/bin/sh

if [ -z "$1" ]
then branch="dev-master"
else branch="$1"
fi

fetch() {
    remoteRepo=$1
    localRepo=$2
    branch=$3
    rev=$(git ls-remote $remoteRepo $branch | cut -f1)
    nix-shell -p nix-prefetch-git jq --run "
      nix-prefetch-git ${localRepo} ${rev} | jq '.url=\"${remoteRepo}\" | .branch=\"${branch}\"'
    "
}

jq > sources.json <<EOF
{
  "nixpkgs":$(fetch https://github.com/bendlas/nixpkgs.git /home/herwig/checkout/nixpkgs $branch),
  "nixos-config":$(fetch https://github.com/bendlas/nixos-config.git /home/herwig/checkout/bendlas-nixos-config master)
}
EOF
